# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-04-30 20:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0002_restpwverifycode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': '字段', 'verbose_name_plural': '字段'},
        ),
        migrations.AlterModelOptions(
            name='restpwverifycode',
            options={'verbose_name': '验证码', 'verbose_name_plural': '验证码'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': '表', 'verbose_name_plural': '表'},
        ),
        migrations.AddField(
            model_name='field',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='已删除', verbose_name='已删除'),
        ),
        migrations.AlterField(
            model_name='field',
            name='alias',
            field=models.CharField(blank=True, default='', help_text='别名', max_length=20, null=True, verbose_name='别名'),
        ),
        migrations.AlterField(
            model_name='field',
            name='is_multi',
            field=models.BooleanField(default=False, help_text='是否为多值字段', verbose_name='是否为多值字段'),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(help_text='字段名，规则：[a-z][a-z-0-9]*$', max_length=20, verbose_name='字段名'),
        ),
        migrations.AlterField(
            model_name='field',
            name='readme',
            field=models.TextField(blank=True, default='', help_text='自述', null=True, verbose_name='自述'),
        ),
        migrations.AlterField(
            model_name='field',
            name='required',
            field=models.BooleanField(default=False, help_text='是否必填', verbose_name='是否必填'),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'string'), (1, 'integer'), (2, 'floating'), (3, 'datetime'), (4, 'date'), (5, 'boolean'), (6, 'Ip')], help_text="字段类型(((0, 'string'), (1, 'integer'), (2, 'floating'), (3, 'datetime'), (4, 'date'), (5, 'boolean'), (6, 'Ip')))", verbose_name='字段类型'),
        ),
        migrations.AlterField(
            model_name='table',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
