# Generated by Django 3.0.6 on 2020-05-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0005_auto_20200508_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': '表', 'verbose_name_plural': '表'},
        ),
        migrations.AddField(
            model_name='field',
            name='order',
            field=models.IntegerField(default=0, help_text='本字段决定了动态字段在动态表中的顺序', verbose_name='顺序号'),
        ),
        migrations.AlterField(
            model_name='field',
            name='alias',
            field=models.CharField(blank=True, default='', help_text='别名(默认"")', max_length=20, null=True, verbose_name='别名'),
        ),
        migrations.AlterField(
            model_name='field',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='已删除(默认False)', verbose_name='已删除'),
        ),
        migrations.AlterField(
            model_name='field',
            name='is_multi',
            field=models.BooleanField(default=False, help_text='是否为多值字段(默认False)', verbose_name='是否为多值字段'),
        ),
        migrations.AlterField(
            model_name='field',
            name='readme',
            field=models.TextField(blank=True, default='', help_text='自述(默认"")', null=True, verbose_name='自述'),
        ),
        migrations.AlterField(
            model_name='field',
            name='required',
            field=models.BooleanField(default=False, help_text='是否必填(默认False)', verbose_name='是否必填'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
