# Generated by Django 3.0.6 on 2020-05-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0008_auto_20200513_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='是否已删除(默认False)', verbose_name='已删除'),
        ),
    ]
