# Generated by Django 3.0.6 on 2020-05-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0009_table_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'string'), (1, 'integer'), (2, 'floating'), (3, 'datetime'), (4, 'date'), (5, 'boolean'), (6, 'ip'), (7, 'image'), (8, 'attachment')], help_text="字段类型(((0, 'string'), (1, 'integer'), (2, 'floating'), (3, 'datetime'), (4, 'date'), (5, 'boolean'), (6, 'ip'), (7, 'image'), (8, 'attachment')))", verbose_name='字段类型'),
        ),
    ]
