# Generated by Django 3.0.6 on 2020-05-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0011_auto_20200515_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='extra_info',
            field=models.TextField(blank=True, default=None, help_text='用于保存字段扩展信息，如可以一个json保存备选项，具体格式不限，与前端约定好即可', null=True, verbose_name='额外信息'),
        ),
    ]
